builds:
  - main: cmd/containerssh/main.go
    binary: "containerssh"
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

dist: build

release:
  github:
    owner: janoszen
    name: containerssh
