name: Deploy docs
on:
  push:
    branches:
      - stable
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      -
        name: Set up Kubernetes
        uses: engineerd/setup-kind@v0.4.0
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --snapshot
      -
        name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
