name: Build
on:
  pull_request:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up Kubernetes
        uses: engineerd/setup-kind@v0.5.0
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
